[workspace]
authors = ["Ash (GitHub@aashen1)"]
channels = ["conda-forge"]
name = "arc-agi-3-human-player"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
human-play = "python -m human_player"
game = "python -m human_player"

[dependencies]
python = ">=3.14.4,<3.15"

[pypi-dependencies]
arc-agi = ">=0.9.8, <0.10"
rich = ">=13.0"
pygame-ce = ">=2.5.7, <3"
