[workspace]
authors = ["Ash (GitHub@aashen1)"]
channels = ["conda-forge"]
name = "arc-agi-3-human-player"
# NOTE: only tested on win-64, other platforms may have issues
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
human-play = "python -m human_player"
game = "python -m human_player"
test = "pytest tests/"

[dependencies]
python = ">=3.12,<3.15"

[pypi-dependencies]
arc-agi-3-human-player = { path = ".", editable = true }
arc-agi = ">=0.9.8, <0.10"
rich = ">=13.0"
pygame-ce = ">=2.5.7, <3"
pytest = ">=9.0.3, <10"
